# index => nom du chemin
#    path: / => chemin et variables get
#    controller: App\Controller\DefaultController::index => namespace\nomfichier
notreAccueil:
    path: /
    controller: App\Controller\IndexController::Accueil
pageDeux:
    path: /deux
    controller: App\Controller\IndexController::Deux
